# Generated by Django 5.0.1 on 2024-02-09 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ytsearchapp", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedVideos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "video_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "video_link",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("video_desc", models.TextField(blank=True, default="", null=True)),
                (
                    "video_image",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("video_views", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "video_published_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "video_channel_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
