# Generated by Django 5.0.1 on 2024-02-09 07:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ytsearchapp", "0002_savedvideos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/profile/"),
        ),
    ]
