# Generated by Django 5.0.1 on 2024-02-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ytsearchapp", "0003_alter_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="forgot_password_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="verification_token",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
